{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "pagina-demo.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "pagina-demo.fullname" . }}
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}

